collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.4548983196727931
color:
  saturation: 0.8398892090190202
  brandStrength: 0.8983300337567925
  rhythmicContrast: 0.1400240727234632
  brandColors:
    - '#FF8000'
    - '#FFD933'
    - '#CCCC52'
    - '#8FB359'
    - '#192B33'
  lightness: 0.7523478192742914
layout_spectrum: 1
name: A Loja da Segurança
